name=MatDrum
version=1.0.0
author=Mattah
maintainer=Mattah <mattah@gmail.com>
sentence=MatDrum is an Arduino library to use that microcontroller as drum MIDI controller.
paragraph=Through this library you can send drum MIDI notes for a virtual drum sotware and also change important parameters presents in many drum modules, such as sensitivity, threshold, scan time and mask time.
category=Sensors
url=https://github.com/Mattaah/mat-drum
architectures=*
includes=MatDrum.h